### ISSUE TITLE
How to return programmatic values and selected options for cmb2 fields 

### ISSUE THREAD

**Issue by pgroot91** [CMB2/CMB2-Snippet-Library#106]
Hi Guys,

I'm looking for some help again! So i'm currently trying to figure out how i'm able to return specific values in cmb2 fields based on a button click with PHP. 

Fields i use are the following: Normal text field, date field, select field, select2 field and radio image.

Now i came with the clever solution :D for the **text** and **date** field to add the "attribute"->"value" solution. Not sure if this is the most clever solution but that seems to work ok. Let me know if there is a better way to archive it!? (**EDIT:** with this solution i don't receive the value anymore)

For the select and radio image field i have no clue how to accomplish that. So what am i doing here? Since the values i got are not 100% the same in the option list, i do a search for a partial match. But now the question is how would i set that specific value found as the option eg on the dropdown based on that button click with PHP?

**Comment by pgroot91** [comment]
Currently trying to set values with ajax

**Comment by tw2113** [comment]
Did you mean to close this? or did you figure it out?
