### ISSUE TITLE
Options page metabox form returns null

### ISSUE THREAD

**Issue by Daronspence** [CMB2/CMB2-Snippet-Library#21]
Using the exact data from this repo 

https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php

with the latest version of CMB2 from github included in a plugin, the `cmb2_metabox_form()` in the `admin_page_display()` function returns null.

How would one go about fixing this?

**Comment by jtsternberg** [comment]
Sorry, I updated the snippet based on changes made in the [CMB2 trunk branch](https://github.com/WebDevStudios/CMB2/tree/trunk). I recommend switching to use the CMB2 trunk branch as the changes in it it will be in the next stable release.

**Comment by jtsternberg** [comment]
Can you verify if this is resolved for you?

**Comment by tw2113** [comment]
Closing for now, we can revisit if we need to.
