### ISSUE TITLE
How to retrieve option set in admin

### ISSUE THREAD

**Issue by architechcro** [CMB2/CMB2-Snippet-Library#34]
Hi,
I'm having difficulties getting option value set in plugin administration.
Administration uses CMB2 metaboxes to enter values.
I implemented a hook on save_post that should read entered values and do some stuff.
I implemented helper function 

```
function myprefix_get_network_option( $key = '' ) {
    return cmb2_get_option( myprefix_admin()->key, $key );
}
```

which in my case looks like 

```
 function sipawp_get_option( $key = '' ) {
    return cmb2_get_option($this->prefix,$key);
}
```

And I don't instantiate admin class as in your example. If I do I get an error "Fatal error: Call to undefined function wp_get_current_user() ..."

I call the sipawp_get_option function from _construct method

```
$this->sipaapp = sipawp_get_option($this->plugin_slug . '_sipaapp');
$this->sipakey = sipawp_get_option($this->plugin_slug . '_sipakey');
```

so I could those params in class function, but I receive this error : Fatal error: Call to undefined function cmb2_get_option()  

Do you have any thoughts on this ?

**Comment by jtsternberg** [comment]
cmb2_get_option is not available until the 'cmb2_init' hook.

> I call the sipawp_get_option function from _construct method

That's too early, unless your constructor is called after 'cmb2_init'

**Comment by architechcro** [comment]
Hi,
Thanks for the answer. Avail, still don't work.
I use a hook 
`add_action('cmb2_init', array($this, 'cmb_sipa_metaboxes'));`
In this hook I initialize CMB boxes - post meta fields and admin options.

My admin option box is defined 
```
 $cmb = new_cmb2_box( array(
				'id' => $this->plugin_slug . '_options',
				'hookup' => false,
				'show_on' => array( 'key' => 'options-page', 'value' => array( $this->plugin_slug ), ),
				'show_names' => true,
		) );
```
and filed in this box

```
$cmb->add_field( array(
				'name' => __( 'SIPA Key', $this->plugin_slug ),
				'desc' => __( 'Access key', $this->plugin_slug ),
				'id' => $this->plugin_slug . '_sipakey',
				'type' => 'text_medium',
			// 'repeatable' => true,
		) );
```

By my logic if I call

`$this->sipakey = cmb2_get_option($this->plugin_slug . '_options', $this->plugin_slug . '_sipakey');
`
would have to return the value of this field.
I get "false" for any field I try to get this way.

I tried also to init cmb2 in my save_post hook with do_action('cmb2_init') and call cmb2_get_option but also get "false" for $this->sipakey value.
In admin options all fields are saved, and values stored.
I can't see what I'm doing wrong.
Sorry if this is to noob :)

**Comment by tw2113** [comment]
Closing for the time being.
