### ISSUE TITLE
How to get an image field from the options page?

### ISSUE THREAD

**Issue by alololox** [CMB2/CMB2-Snippet-Library#38]
Hi!
First of all, thank you for this awesome plugin :)

I'm trying to get an image field to show from the site options page, but am having some trouble trying to figure out the appropriate code to call it. I'm not sure how to fit your example into the `wp_get_attachment_image()` function. I've tried..

```
<?php $image = wp_get_attachment_image( myprefix_get_option( 'footer_image_id', 1 ) ); echo $image ?>
<?php wp_get_attachment_image( myprefix_get_option( 'footer_image_id', 1 )); ?>
<?php wp_get_attachment_image( myprefix_get_option( 'footer_image', 1 )); ?>
```

And can't seem to get it to work. Please point me in the right direction!

**Comment by bgturner** [comment]
You might have already figured this out, but it looks like you need to echo out the result of `wp_get_attachment_image()`.

Try this:
`<?php echo wp_get_attachment_image( myprefix_get_option( 'footer_image_id', 1 )); ?>`

Also, when I tried this in my own setup, I didn't need that second parameter of `1`, so this might work for you as well:

`<?php echo wp_get_attachment_image( myprefix_get_option( 'footer_image_id' ) ); ?>`

**Comment by tw2113** [comment]
Closing as most likely resolved and no longer an issue.
