### ISSUE TITLE
changed Save Button

### ISSUE THREAD

**Issue by tourscaner** [CMB2/CMB2-Snippet-Library#54]
Hello
I am using this code
But I want to change the Save Button
I want to work
This code
`<input type="submit" name="step2" id="step2" class="btn_orange" value="<?php _e( 'Continue &rsaquo;&rsaquo;', APP_TD ); ?>" [/>`

[<a href="http://tourscaner.ir/antalya">تور آنتالیا</a>](url)

**Comment by jtsternberg** [comment]
> I am using this code

Which code?

**Comment by tourscaner** [comment]
sorry
this code
cmb2-front-end-submit.php
https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php

But I want to change the Save Button
with the
This code
<input type="submit" name="step2" id="step2" class="btn_orange" value="<?php _e( 'Continue &rsaquo;&rsaquo;', APP_TD ); ?>" [/>

Thanks

**Comment by jtsternberg** [comment]
Change [this line](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php#L136) to:
```php
$output .= cmb2_get_metabox_form( $cmb, 'fake-oject-id', array(
	'save_button' => '',
	'form_format' => '<form class="cmb-form" method="post" id="%1$s" enctype="multipart/form-data" encoding="multipart/form-data"><input type="hidden" name="object_id" value="%2$s">%3$s<input type="submit" name="step2" id="step2" class="btn_orange" value="%4$s" /></form>',
) );
```

**Comment by tourscaner** [comment]
hi jtsternberg
Thanks for your response
I've changed to
`$output .= cmb2_get_metabox_form( $cmb, 'fake-oject-id', array(
	'save_button' => '',
	'form_format' => '<form name="mainform" id="mainform" class="form_step" action="<?php echo appthemes_get_step_url(); ?>" method="post" enctype="multipart/form-data"><input type="hidden" name="ID" value="<?php echo esc_attr( $listing->ID ); ?>" /><input type="hidden" name="action" value="<?php echo esc_attr( $action ); ?>" />%3$s<input type="submit" name="step1" id="step1" class="btn_orange" value="Continue" /></form>',
) );`
But that does not work

**Comment by tw2113** [comment]
Closing as likely resolved or no longer an issue.
