### ISSUE TITLE
Autocomplete Field Type doesn't work if repeating

### ISSUE THREAD

**Issue by wpalchemist** [CMB2/CMB2-Snippet-Library#57]
I set up an autocomplete field type using the example here: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/custom-field-types/autocomplete-field-type.php

Whether I copy and paste this code exactly, or modify it for my own needs, the fields do not work as repeating fields.  When you click "add", you get a new row that has only a "remove" button, and no input field.  Screenshot:
![image](https://cloud.githubusercontent.com/assets/16658165/22003922/30fdc1b2-dc0c-11e6-9565-6dcfc920f2e2.png)

I haven't yet found a way to get the repeating fields to work.  Any suggestions for how to do that?

**Comment by jtsternberg** [comment]
That snippet was submitted by @johnsonpaul1014, so we'll see if he has any feedback.

**Comment by jtsternberg** [comment]
Also, you should probably include your custom field registration code for review.

**Comment by johnsonpaul1014** [comment]
This is working for us in production, but there may have been some modifications made since I uploaded the snippet.  I'll check the code and get back to you.

**Comment by johnsonpaul1014** [comment]
Please check out the new pull request I just made.  This is our production code and should hopefully work better for you.

**Comment by wpalchemist** [comment]
Thanks for the quick response!

Unfortunately, it's still not working.... This is an improvement, because the hidden field does show up in the HTML, but the screenshot still looks the same - the input field for the user is still not showing up.

**Comment by johnsonpaul1014** [comment]
Are you just using the example?  What version of WordPress/CMB2 are you using?  Because for testing I installed the newest WordPress, CMB2 and the plugin and it worked perfectly.  If you are testing some of your own registration code, could you include it?  The options array format has changed, so that may be the issue if you are using your own code.


Paul


________________________________

**Comment by wpalchemist** [comment]
I tried removing all of my code, and using just the example code, and I still get the same thing.  I'm using WP 4.7.1 and CMB2 2.2.3.  I disabled all plugins, and switched to Twenty Seventeen, and the input field is still not showing up.  I've tried this on two separate sites, and getting the same problem on each.

I'll continue to poke at it and see if I can figure out what's going on.

**Comment by johnsonpaul1014** [comment]
Are you getting any errors in the JavaScript console?

Sent from my iPhone

On Jan 17, 2017, at 2:08 PM, Morgan Kay <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried removing all of my code, and using just the example code, and I still get the same thing. I'm using WP 4.7.1 and CMB2 2.2.3. I disabled all plugins, and switched to Twenty Seventeen, and the input field is still not showing up. I've tried this on two separate sites, and getting the same problem on each.

I'll continue to poke at it and see if I can figure out what's going on.

-

**Comment by wpalchemist** [comment]
Nope, console is empty.  Very mysterious.

**Comment by wpalchemist** [comment]
I have made some progress towards figuring this out.... From what I can tell, the issue is that CMB2's repeat function doesn't acknowledge the existence of the echoed input field.

In other words, the repeater won't repeat this line:
`echo '<input type="hidden" size="50" value="'.htmlspecialchars($value).'" class="'.$id.'-autocomplete"/>';`
(you know, the important line ;) )

However, if I do this instead:
`echo $field_type_object->text();`
then when you add another row the field does show up.  But autocomplete doesn't work on that row.... However, if you do both, then both fields to work as autocomplete.  So my really ugly solution for the time being is this:
`echo $field_type_object->text();
echo '<input type="hidden" size="50" value="'.htmlspecialchars($value).'" class="'.$id.'-autocomplete"/>';`

That's ugly, but it at least work for now.  Maybe tomorrow with a fresh brain I'll be able to get it to work without echoing the extraneous hidden field.

**Comment by tw2113** [comment]
Closing as apparently works now, or at least at the time of the previous reply.

Thanks.
