### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by elarion83** [CMB2/CMB2-Snippet-Library#59]
Hi ! Thanks for this plugin, it's totally awesome !

But it's been 2hours i'm playing with two issue : 
- i use the front end submit form example but i cant see the meta boxe in my wp admin and can't edit
OR
- I use the front end edit form example but i can't see the meta boxes in my wp admin and can't submit 

I thinks that there's something I'm missing. 

I'm loading in my functions.php in order : 
my users metaboxe file
my submit propertie file
and my property edit file

thx !

**Comment by tw2113** [comment]
Closing for the time being. If @elarion83 needs to return to it, we can at that point.
