### ISSUE TITLE
Is there any way to use Yoast Seo Analysis for custom meta boxes?

### ISSUE THREAD

**Issue by OksanaRomaniv** [CMB2/CMB2-Snippet-Library#60]
Hello,

Firstly, thank you for your great code!

I just wonder if there is any way to force Yoast Seo Analysis to include text in custom meta boxes? I am using a repeatable group for creating slideshow and all the content of the post is in meta boxes.

Kind Regards,
Oksana

**Comment by jtsternberg** [comment]
There is an addon [listed in the resources](https://github.com/WebDevStudios/CMB2#other-helpful-resources) for doing that.

**Comment by TheNewGuy16** [comment]
Hey guys just so its out there the yoast for cmb2 wont analyze group wysiwyg fields.  But there is a work around

So I looked into the js used for this in the Yoast for CMB2 plugin and it seems the plugin is just finding input fields with the attribute of yoast-analysis but for group fields and wysiwyg editors the plugin would not add the attribute. So if you add an extra_class instead to the wysiwyg editor using its options in cmb2, then add that textarea class to the js .each function and .on function you will now be able to analyze the group wysiwyg editors.

**so in the js file for Yoast for CMB2 plugin I added the textarea and class in bold**

$('#post-body').find(
'input[yoast-analysis=1]:not(".cmb2-upload-file-id"), textarea[yoast-analysis=1],**textarea.yoast-analysis**'
).on('keyup paste cut click', function() {

$('#post-body').find(
'input[yoast-analysis=1]:not(".cmb2-upload-file-id"), textarea[yoast-analysis=1],**textarea.yoast-analysis**'
).each(function() {

then in the functions file for your plugin or theme you just need to add an extra editor_class using the CMB2 wysiwygs field options

editor_class' => 'yoast-analysis', // add extra class(es) to the editor textarea for yoast analysis

you can find the docs here [https://github.com/CMB2/CMB2/wiki/Field-Types#wysiwyg]( https://github.com/CMB2/CMB2/wiki/Field-Types#wysiwyg)

it does work and is nice to be able to just add a class and use it to add the text to the data return for yoast  I am new to this and not sure if I should fork the git and add this stuff

**Comment by tw2113** [comment]
Closing as a non issue for CMB2/Library files.
