### ISSUE TITLE
Not mainly an issue but lack of information (I can be completely wrong)

### ISSUE THREAD

**Issue by parvvee** [CMB2/CMB2-Snippet-Library#72]
I understand that  when we  create  repeatable  group data  , it saves the in wp_postmeta table in serialized form.  But if I try to change / update the section of content (lets say a shortcode  in wysiwyg)  in bulk   as the repeatable data cant be detected by regular like or %like% queries. Even if I try  to use  regular expressions  i am not sure if that works... Any guidance on figuring out with bulk find and replacing of cmb2  repeatable fields will be of great help.
Thank you.

**Comment by tw2113** [comment]
Can definitely sympathize with this issue as a whole, but to be fair it's also not an issue exclusive to CMB2. Any code/plugin/theme that ends up storing meta this way would be affected. I can't recall quite how I did some similar stuff, but I know I've done "muddy" WP_Query calls with metaqueries that had to deal with this in the past. I'd need to track down where, to provide an answer for how that worked.

That said, closing as not CMB2 specific. Conversation can still go on if needed in the issue.
