### ISSUE TITLE
Front end forms

### ISSUE THREAD

**Issue by emwebber** [CMB2/CMB2-Snippet-Library#76]
I've used CMB2 extensively for additional or custom functions and processes on the back end, but i don't have that same understanding or comfort-level when trying it out for front end applications.

So, I'm in need of some guidance using CMB2 to create front-end forms. I read your New Post Submission Form sample in the Snippet Library, and jcchavezs's cmb2-conditionals but I'm still struggling to get this out there. 

Is it possible that you guys could do a front-end form demo with documentation, that doesn't require the use of a shortcode, for something like a registration form with a couple conditional fields?

You guys have been awesome in the past where support was concerned and i'm hoping you can help me out again! :)

**Comment by tw2113** [comment]
Closing as hopefully fixed/resolved since originally opening. If the original poster comes back, we can re-visit.
