### ISSUE TITLE
Appearance

### ISSUE THREAD

**Issue by chrisdrake** [CMB2/CMB2-Snippet-Library#78]
Is there any easy way apart from creating custom css rules to get the appearance of a settings page to match the look of the WordPress settings pages?

**Comment by jtsternberg** [comment]
You could use JS to remove the `cmb2-options-page` wrap class. There are various php ways to do it as well (like using your own `display_cb`: https://github.com/CMB2/CMB2/wiki/Field-Parameters#display_cb)

**Comment by chrisdrake** [comment]
Many thanks, Justin. And keep up the good work. This is hands down the best custom fields library for WP.

**Comment by jtsternberg** [comment]
Thank you! Is it ok to close this issue then?
