### ISSUE TITLE
Fields not saving when split_value is true

### ISSUE THREAD

**Issue by clkmediaco** [CMB2/CMB2-Snippet-Library#80]
Thanks for a great add-on field!

Not sure if i'm unique in this issue, but i could use some help...

Using the address field type (w/repeatable), and it saves fine when 'split_value'=>false and it's a serialized single meta_key, but when it's set to true no values get saved, and no meta_keys get created.

It seems like the $value parameter is just not getting passed with meta values with the filter.

Running the latest CMB2 and genesis. Any guidance would be appreciated.

Thanks in advance

**Comment by tw2113** [comment]
@clkmediaco Did you ever get this figured out or did it get moved on from?

**Comment by clkmediaco** [comment]
@tw2113 never did solve this one, had to go a different direction on it.

**Comment by tw2113** [comment]
Noted. I'm going to try and investigate and see if there's anything that needs done for future usecases.

Thanks for the feedback and update though.

**Comment by tw2113** [comment]
Just as some followup. I saw that it was saving just fine. However, it's the re-display into the individual inputs that's broken/incomplete in regards to the snippet library.

I am going to be tinkering with it and see if I can get that amended to make it work better.

**Comment by tw2113** [comment]
See db3a59733d4d808a0b78836316cf5e164e307e87 and the updated files for this custom field type.
