### ISSUE TITLE
Snippet "options-pages-with-tabs-and-submenus" : where is CMB2 2.4.0 ?

### ISSUE THREAD

**Issue by alexis-magina** [CMB2/CMB2-Snippet-Library#89]
The snippet options-pages-with-tabs-and-submenus doesn't work :  
It uses tabs feature from an unknown version 2.4.0 of CMB2. 
Where is this version ? 
Is there a working snippet to add an option page with tabs, with only CMB2 base plugin, and without using cmb2-tabs 3rd party plugin ?

**Comment by jtsternberg** [comment]
You can use the trunk branch of CMB2 until the 2.4.0 release which should be very soon (as soon as I get a chance to clean the release up)
