### ISSUE TITLE
Title throwing error

### ISSUE THREAD

**Issue by StanSkrivanek** [CMB2/CMB2-Snippet-Library#90]
Im trying this example snippet in my custom theme. I have placed shortcode `[cmb_frontend_form]` on page and Im getting error on submit with code checking title : **_There was an error in the submission: Please enter a new title._**

```php	
// And that the title is not the default title
    if ($cmb->get_field('submitted_post_title')->default() == $_POST['submitted_post_title']) {
        return $cmb->prop('submission_error', new WP_Error('post_data_missing', __('Please enter a new title.')));
    }
```

When I do not equal `!==` all is working fine but title can be identical (identical string) with already published (or pending) article :(
Any Idea where to look into?

**Comment by tw2113** [comment]
@StanSkrivanek i know it's been half a year but is this still an issue at all? or did you get it resolved?

**Comment by StanSkrivanek** [comment]
Im sorry, but it was for side project and it is so long that I don't remember if I have had find solution or not. Usually I get reported back when problem was sorted out ...  But you can close this issue. BTW CMB2 is really great tool and when I will go back to WP dev I will use it for sure.

**Comment by tw2113** [comment]
No worries, and thanks for the feedback. Hope your projects are going well :D
