### ISSUE TITLE
Overriding WP Core post_status field issue

### ISSUE THREAD

**Issue by pgroot91** [CMB2/CMB2-Snippet-Library#95]
I went true the examples and try to archive the following i want to be able to save to the post status field. This succeeds after first initial save but if you then save it again it saves a wordpress core status value instead of the selected option.

my code looks like this:

```
function yourprefix_filter_publish_box( $post ) {
	$cmb = cmb2_get_metabox( '_yourprefix_publish_box' ); // Must match the box ID.
	if ( in_array( $post->post_type, $cmb->prop( 'object_types' ), true ) ) {
		$cmb->show_form();
	}
}
add_action( 'cmb2_admin_init', 'yourprefix_cmb2_fields' ); 
	  


function yourprefix_cmb2_fields() {
	$prefix = '_yourprefix_';
	$cmb = new_cmb2_box( [
		'id'           => $prefix . 'publish_box',
		'object_types' => [ 'stock' ],               // Any public post type.
		'show_names'   => false,                    // Disables the display for the CMB2 label.
	] );
		
	$cmb->add_field( array(
		'before' => '<label for="post_status">' . __( 'Status', 'cmb2' ) . '</label>',
		'id'   => 'post_status',
		'type' => 'select',
		'options' => array(
			'available' => __( 'Available', 'cmb2' ),
			'reserved'  => __( 'Reserved', 'cmb2' ),
			'expected'  => __( 'Expected', 'cmb2' ),
			'sold' 		=> __( 'Sold', 'cmb2' ),
		),
	));
}
add_action( 'post_submitbox_misc_actions', 'yourprefix_filter_publish_box' );

function cmb2_override_post_status_display( $data, $post_id ) {
	return get_post_field( 'post_status', $post_id );
}

add_filter( 'cmb2_override_post_status_meta_value', 'cmb2_override_post_status_display', 10, 2 );

add_filter( 'cmb2_override_post_status_meta_save', '__return_true' );
```

Any clue what is causing this behavior?
 
At this stage i haven't tested the main examples to check if the behavior is the same.

**Comment by pgroot91** [comment]
what i see from the post perspective the value changes to pending... I think i need to dive a bit deeper to understand whats going on with the post_status of wp. Guess this is not an issue because of above setup would be awesome if someone can confirm my suspicion.

**Comment by tw2113** [comment]
I guess my question is what is your purpose with this? Just a visual status "oh this post is available" or "Aww drat, this one is sold". Or do you expect to do queries against the current status? Asking because maybe a meta query would suffice. If you know you're going to have a ton of them, and are worried about eventual performance, maybe treat them as taxonomy terms.

Most things I've seen around the official post_status stuff is generally complicated and nowhere near as easy to customize/hook into, as it could be. So my suggestion is usually to just fake it with a different content value elsewhere.

**Comment by pgroot91** [comment]
@tw2113 probabaly you're right that could save me some trouble in the end. I think i Will try to go with what you suggest me here and see if i can come up with another solution. 

The reason why i was going the route of custom_post_status is the ease of displaying the links and count of those to statuses in the admin post table.

**Comment by tw2113** [comment]
I know there are filters and whatnot to add your own that you could get post/term data with, if you're game for that route
