### ISSUE TITLE
limit-number-of-repeat-fields in taxonomy page

### ISSUE THREAD

**Issue by Moumokhtar** [CMB2/CMB2-Snippet-Library#99]
im trying to use the example from the library it worked fine in my custom post type , but when i tried it in my custom taxonomy script does not get attached ... im not sure but i think that the 
`add_action( 'cmb2_after_post_form_type_form_metabox', 'js_limit_field_repeat', 10, 2 );` did not work cus when i inspect i can not find the script my term metabox id is 'type_form_metabox' .. im not sure whats wrong i used the same action on my custom post type metabox and it worked ... it should be `cmb2_after_post_form_{my_metabox_id}`

**Comment by tw2113** [comment]
Looking at the source code, this is the hook in question, if I'm not mistaken:

```
/**
 * Hook after form form has been rendered
 *
 * The dynamic portion of the hook name, $this->cmb_id, is the meta_box id.
 *
 * The first dynamic portion of the hook name, $object_type, is the type of object
 * you are working with. Usually `post` (this applies to all post-types).
 * Could also be `comment`, `user` or `options-page`.
 *
 * @param int    $object_id   The ID of the current object
 * @param array  $cmb         This CMB2 object
 */
do_action( "cmb2_after_{$object_type}_form_{$this->cmb_id}", $object_id, $this );
```

Since you're working on a taxonomy page, the hook you should be trying with is `cmb2_after_term_form_type_form_metabox`

**Comment by Moumokhtar** [comment]
man i looked all over the docs for this but i maybe missed it .. thanks alot !

**Comment by tw2113** [comment]
The `term` key word may not have been added or simply missed in those documentation spots, for what it's worth.
